### ISSUE TITLE
Build error: no associated item named `ISize` found for type `glib::types::Type` in the current scope

### ISSUE THREAD

**Issue by macropas** [GuillaumeGomez/process-viewer#10]
First build error: no associated item named `ISize` found for type `glib::types::Type` in the current scope. line 80
rustc 1.6.0 (c30b771ad 2016-01-19)
![rust - process_viewer-src-process_viewer rs - eclipse platform _001](https://cloud.githubusercontent.com/assets/7488502/13387934/6150b068-dec4-11e5-885d-8dd69483c140.png)

**Comment by GuillaumeGomez** [comment]
I think I didn't updated process viewer to the last glib version yet. If you want to keep it working, you should replace the glib version in the `Cargo.toml` file. Otherwise I'll update it this evening.

**Comment by macropas** [comment]
Thank you :-)

**Comment by GuillaumeGomez** [comment]
And done. Enjoy it. :)
