### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by jrop** [GuillaumeGomez/process-viewer#108]
I don't want this to be a bash against Electron (some of my favorite apps are built with Electron), but I did want to say I found the following refreshing:

```
ls -lh /Users/me/.cargo/bin/process_viewer
-rwxr-xr-x  1 me  me   1.3M Mar 21 16:37 /Users/me/.cargo/bin/process_viewer
```

Nice job on the app!

**Comment by GuillaumeGomez** [comment]
The binary size could get way smaller but I didn't look at all on optimizations on this side. But anyway, thanks for your comments, I appreciate it. ;)
