### ISSUE TITLE
network usage does not show a graph

### ISSUE THREAD

**Issue by omac777** [GuillaumeGomez/process-viewer#152]
the default gnome system-viewer displays 3 things in the default resources: cpu, memory and network usage.
rust process-viewer doesn't display network in a graph alongside the cpu and memory.  It would be ideal if there was an option to make that happen.

Thank you for listening.

**Comment by GuillaumeGomez** [comment]
Just double-click on the network you're interested in, a dialog will open with more information and graphs. :)
