### ISSUE TITLE
No releases?

### ISSUE THREAD

**Issue by GirkovArpa** [GuillaumeGomez/process-viewer#170]
I wanted to try this out real quick but ... there's nothing in the Releases.

**Comment by GuillaumeGomez** [comment]
Sorry but I don't understand what you're talking about. What releases? Generally, people install it like this: `cargo install process-viewer`. Are you referring to something else?

**Comment by GirkovArpa** [comment]
I admit I only glanced at the readme and thought it looked cool.  I assumed there was an executable in the Releases I could run, but maybe I am confused 😄 Perhaps I shall build it myself from source.
