### ISSUE TITLE
 repository doesn't contain the 'src/procs.rs' path in 'master

### ISSUE THREAD

**Issue by danger89** [GuillaumeGomez/process-viewer#188]
I just want to mention that my GitHub account just suddenly mentioned your project. You are missing `src/procs.rs` file in your master branch!?

![image](https://user-images.githubusercontent.com/628926/170608709-d5423399-57c3-4a20-82f6-e5c41052cbe2.png)

I also have no clue what the hack is going on with GitHub.com.

But just that know you 👍🏽 .

Regards,
~ Melroy

**Comment by danger89** [comment]
Next time I maybe see random passwords in github who knowns

**Comment by GuillaumeGomez** [comment]
There is no such file indeed. Not sure what the issue sure is so closing.
