### ISSUE TITLE
Change units

### ISSUE THREAD

**Issue by Anachron** [GuillaumeGomez/process-viewer#2]
Would be good to display kb/mb/gb instead of a raw integer.

**Comment by GuillaumeGomez** [comment]
I wanted to set "memory (in mb)" as column name, but I never did...

**Comment by GuillaumeGomez** [comment]
And that's now done.

**Comment by Anachron** [comment]
@GuillaumeGomez maybe it's better to use gb instead of GB?

https://github.com/GuillaumeGomez/process-viewer/blob/master/src/process_viewer.rs#L259-L267

(Please also note the code is redundant and could be outsourced into a public function)

**Comment by GuillaumeGomez** [comment]
I'm not sure about how abbreviations work in english, I should search a little around (but I guess it's gb). And yes, the code for now is very ugly. I started very recently to add structs and clarify everything a little bit but that's still far more end result (I want to add a lot more stuff but I have to lessen cpu usage of this application before that).

**Comment by Anachron** [comment]
There is a difference between GB and gb.
GB = 1000 units, gb = 1024 units. The second one is more accurate in a computer storage system, since everything is based on it.

**Comment by GuillaumeGomez** [comment]
Oh okay, I didn't know there was a difference like this ! Wanna make a PR to change it ?

**Comment by Anachron** [comment]
Well, we never stop learning. =)

Can't submit a PR right now, as I'm not on a development machine, either you wait until I'm home or do it yourself.

**Comment by GuillaumeGomez** [comment]
It can totally wait, I'm not on my computer either.
