### ISSUE TITLE
When enabling CPU graph view, legend is rendered off-window

### ISSUE THREAD

**Issue by genodeftest** [GuillaumeGomez/process-viewer#29]
Steps to reproduce:
1. open "System usage" tab
2. check "Graph view"
3. watch GUI

What happens:
Labels "Graph view", "process 1" (shouldn't that be "CPU 1" btw?) , "process 2", … are partially cut of.

**Comment by GuillaumeGomez** [comment]
Hum... Tested on 3 different computers and don't have the issue. Do you have a screenshot by any chance? (and I actually don't know how to translate it in english, so I guess CPU would be better?).

**Comment by genodeftest** [comment]
Github upload is broken, so I have to use imgur: https://imgur.com/mBHy4yE

This is happening on Wayland, but not on x11 or on wayland with x11 backend. Might be an issue in Gtk+.

**Comment by GuillaumeGomez** [comment]
I don't think it's because of GTK. To resize the layout containing the graph and the list, I have to resize the graph by hand. So I think I update it incorrectly. I'll try to fix it as soon as possible.

**Comment by genodeftest** [comment]
I see a scrolled pane inside the window instead of the window having enough size. I can resize the window, but the content always is ~20px wider than the window, always leading to cut off content. I've seen something similiar before with SWT (a Java GUI toolkit based on Gtk+ on linux): https://bugzilla.redhat.com/show_bug.cgi?id=1255007

On wayland, updating the graph doesn't work either. It will only be refreshed when the window gets or loses focus.

**Comment by GuillaumeGomez** [comment]
> On wayland, updating the graph doesn't work either. It will only be refreshed when the window gets or loses focus.

Ah. This, however is a GTK bug I think.

**Comment by genodeftest** [comment]
All of the misbehaviors described above are fixed by updating Gtk+ from 3.18.x to 3.20.x. Sorry for the noise.

**Comment by GuillaumeGomez** [comment]
Glad to hear it!
