### ISSUE TITLE
Too high CPU

### ISSUE THREAD

**Issue by Anachron** [GuillaumeGomez/process-viewer#3]
This tool generates about 10-25% of a single core, using Linux Mint 17.1 Rebecca with Cinnamon 2.6 (8GB ram, 8 cores 3.1ghz, 2GB intel HD 4000, 500GB SSD).

**Comment by GuillaumeGomez** [comment]
I have an issue too. Comparing to `htop`, my values are ~3% too high. I'm still trying to fix the computation (if you have any clue, it's very welcome !).

**Comment by Anachron** [comment]
Can't seem to find any issues so far with the source, will keep investigating.

**Comment by GuillaumeGomez** [comment]
I launched two processes (each one use ~20% of a processor) and the values were even more wrong. The problem gets deeper.

**Comment by Anachron** [comment]
I've done some digging and was asking, how did you come to this calculation?
https://github.com/GuillaumeGomez/sysinfo/blob/master/src/process.rs#L77

I'm not sure why but for me this looks not correctly...

**Comment by GuillaumeGomez** [comment]
I couldn't find the old computation I used back in high school so I tried some, based on my comprehension of `man proc`.

**Comment by Anachron** [comment]
So I'm guessing this is how you did it?

http://stackoverflow.com/a/1424556

https://github.com/GuillaumeGomez/process-viewer/blob/master/src/process_viewer.rs#L232
https://github.com/GuillaumeGomez/sysinfo/blob/master/src/process.rs#L77

So you actually pass a smaller float and recalculate it in %. (`*100`)

It should be correctly, but maybe some values are getting messed up when reading them from file-system? Did you do some debugging to check whether it's always the correct process-data being returned to calculate? (From the FS)

**Comment by GuillaumeGomez** [comment]
I did, but certainly not enough. I spent my w-e trying to create `TreeSortable` trait in `gtk` in order to allow sorting/filtering. Unfortunately, I discovered an ICE so we'll have to wait for this haha.

I'll try to see this evening if there isn't bad values in computation.

**Comment by Anachron** [comment]
I'm guessing you are talking about this ICE:
https://github.com/rust-lang/rust/issues/26076

When is the code refactoring planned?
As I've experienced, it's better to do it in the beginning when the LOC is still small.

**Comment by GuillaumeGomez** [comment]
As soon as @gkoz has finished it.

**Comment by GuillaumeGomez** [comment]
This issue is now solved. I close this issue.
