### ISSUE TITLE
sysinfo when building with Rust 1.5

### ISSUE THREAD

**Issue by nachoba** [GuillaumeGomez/process-viewer#6]
Hi,
When I try to build using Rust 1.5 I get the following error:
sysinfo.rs:11:1  #[feature] may not be used on the stable release channel.
sysinfo.rs:11 #![feature(convert)]

Any clue?
Thanks!

**Comment by Ticki** [comment]
You have to build with rust nightly.

**Comment by GuillaumeGomez** [comment]
@Ticki: Thanks !
Just like he said. I'm wondering if the convert feature could be removed
now... I'll test.

**Comment by GuillaumeGomez** [comment]
It doesn't build with the last gtk version. I'm having issue with the closures.

**Comment by GuillaumeGomez** [comment]
It's fixed. I close this issue.

**Comment by GuillaumeGomez** [comment]
It no longer needs nightly, it compiles and work fine on stable as well.
