### ISSUE TITLE
Window is not set as floating by default

### ISSUE THREAD

**Issue by ticki** [GuillaumeGomez/process-viewer#7]
Noticeable if you're using a tiling window manager.

**Comment by GuillaumeGomez** [comment]
Thanks, I'll fix it.

**Comment by Ticki** [comment]
Thanks, I'm really happy with this little program :)

**Comment by GuillaumeGomez** [comment]
Well, once I have fixed the closure issue, it'll be quick. Also, if you
want to give it a try, please do. :)

**Comment by Ticki** [comment]
I'm just writing this weeks edition of TWiRx. Will look at it when I get time.

**Comment by Ticki** [comment]
@GuillaumeGomez Could you push what you have at this point (in a different branch, of course).

**Comment by GuillaumeGomez** [comment]
I already did in the master branch. The previous version didn't build
anyway so there was no point to work on another branch.

**Comment by GuillaumeGomez** [comment]
I'll fully switch to `Arc` and `Mutex`, it'll be easier. Weird that this closure needs objects to be `Send+Sync`...

**Comment by Ticki** [comment]
Yeah, I ran into that problem as well.

**Comment by GuillaumeGomez** [comment]
Like I said on the other issue, the code compiles again (not very beautiful but whatever...). I let you set the window as floating by default. :)

**Comment by GuillaumeGomez** [comment]
Hi @Ticki! So I'm updating the process-viewer and I need a confirmation from you: do you need a Popup window type or a toplevel one?

https://github.com/gtk-rs/sys/blob/master/gtk-sys/src/lib.rs#L1459

**Comment by Ticki** [comment]
TopLevel, I guess.

**Comment by GuillaumeGomez** [comment]
It's already Toplevel, let's try with Popup.
