### ISSUE TITLE
100% CPU load on one core; Lags

### ISSUE THREAD

**Issue by genodeftest** [GuillaumeGomez/process-viewer#73]
Even with graphs disabled, running the latest process-viewer from git master eats one core of my CPU. As a result, it is unable to process input events in time and feels very laggy.

This issue is present for both debug and release builds, although it is less bad on release builds. I've compiled process-viewer using
rust-1.22.1-1.fc27.x86_64
cargo-0.23.0-1.fc27.x86_64
on Fedora 27 on a 4.14.3-300.fc27.x86_64 #1 SMP kernel.

**Comment by GuillaumeGomez** [comment]
What are your computer specs? If it doesn't come from that, I'll try to setup a fedora VM.

**Comment by genodeftest** [comment]
> What are your computer specs? If it doesn't come from that, I'll try to setup a fedora VM.

```
$ cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 37
model name	: Intel(R) Core(TM) i5 CPU         650  @ 3.20GHz
stepping	: 2
microcode	: 0xe
cpu MHz		: 1200.000
cache size	: 4096 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 popcnt aes lahf_lm tpr_shadow vnmi flexpriority ept vpid dtherm ida arat
bugs		:
bogomips	: 6422.92
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
```

GPU: Intel integrated GPU.

**Comment by GuillaumeGomez** [comment]
I just tested on my ubuntu (2 cores, 4 GB RAM) and it uses up to 6%... Are you sure you're using the last version? If not, I can just ask you to use `perf` and tell me what's wrong. I have no other idea for the moment...

**Comment by GuillaumeGomez** [comment]
I just thought: do you run it with `--release`? If not, please try.

**Comment by genodeftest** [comment]
What perf data do you need? I'm not familiar with that tool, sorry. Btw: with the latest commits (as opposed to a few days ago) the CPU is only at ~15% on one core.

> I just thought: do you run it with `--release`? If not, please try.

Yes, I do.

**Comment by GuillaumeGomez** [comment]
Strange... Well, if it works at ~15%, I suppose it's fine. I'll close this issue for the moment then. Don't hesitate to reopen it if the problem comes back.
